services:
  - type: web
    name: portfolio-analyzer
    env: python

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: ./start.sh

    autoDeploy: true

    envVars:
      - key: MONGO_URI
        value: ${MONGO_URI}

      - key: MONGO_DBNAME
        value: ${MONGO_DBNAME}

      - key: SECRET_KEY
        value: ${SECRET_KEY}

      - key: KITE_API_KEY
        value: ${KITE_API_KEY}

      - key: KITE_API_SECRET
        value: ${KITE_API_SECRET}

      - key: KITE_ACCESS_TOKEN
        value: ${KITE_ACCESS_TOKEN}

      - key: BASE_URL
        value: ${BASE_URL}

      - key: CLIQ_INCOMING_WEBHOOK
        value: ${CLIQ_INCOMING_WEBHOOK}

      - key: APP_INTERNAL_SECRET
        value: ${APP_INTERNAL_SECRET}
